managers_dict = {
    29: {
        "name": "Roberto Mancini",
        "nationality": "Italy",
        "club": "Manchester City",
        "date_start": "2009-12-19",
        "date_end": "2013-05-13",
        "fotmob_id": 78702,
        "status": "memorable",
    },
    30: {
        "name": "Antonio Conte",
        "nationality": "Italy",
        "club": "Chelsea FC",
        "date_start": "2016-07-01",
        "date_end": "2018-07-13",
        "fotmob_id": None,
        "status": "memorable",
    },
    31: {
        "name": "Antonio Conte",
        "nationality": "Italy",
        "club": "Tottenham Hotspur",
        "date_start": "2021-11-02",
        "date_end": "2023-03-26",
        "fotmob_id": None,
        "status": "memorable",
    },
    32: {
        "name": "Ralf Rangnick",
        "nationality": "Germany",
        "club": "Manchester United",
        "date_start": "2021-12-03",
        "date_end": "2022-05-31",
        "fotmob_id": 148889,
        "status": "memorable",
    },
    33: {
        "name": "Harry Redknapp",
        "nationality": "England",
        "club": "Tottenham Hotspur",
        "date_start": "2008-11-26",
        "date_end": "2012-06-14",
        "fotmob_id": None,
        "status": "memorable",
    },
    34: {
        "name": "Claudio Ranieri",
        "nationality": "Italy",
        "club": "Leicester City",
        "date_start": "2015-07-13",
        "date_end": "2017-02-23",
        "fotmob_id": 78620,
        "status": "memorable",
    },
    35: {
        "name": "Frank Lampard",
        "nationality": "England",
        "club": "Chelsea FC",
        "date_start": "2023-04-06",
        "date_end": "2023-06-30",
        "fotmob_id": 942244,
        "status": "memorable",
    },
    36: {
        "name": "Frank Lampard",
        "nationality": "England",
        "club": "Everton FC",
        "date_start": "2022-01-31",
        "date_end": "2023-01-23",
        "fotmob_id": 942244,
        "status": "memorable",
    },
    37: {
        "name": "Sean Dyche",
        "nationality": "England",
        "club": "Everton FC",
        "date_start": "2023-01-30",
        "date_end": "today",
        "fotmob_id": 24581,
        "status": "memorable",
    },
    38: {
        "name": "David Moyes",
        "nationality": "Scotland",
        "club": "Everton FC",
        "date_start": "2002-03-14",
        "date_end": "2013-06-30",
        "fotmob_id": 78626,
        "status": "memorable",
    },
    39: {
        "name": "David Moyes",
        "nationality": "Scotland",
        "club": "Everton FC",
        "date_start": "2013-07-01",
        "date_end": "2014-04-22",
        "fotmob_id": 78626,
        "status": "memorable",
    },
    40: {
        "name": "Frank de Boer",
        "nationality": "Netherlands",
        "club": "Crystal Palace",
        "date_start": "2017-07-01",
        "date_end": "2017-09-11",
        "fotmob_id": 240019,
        "status": "memorable",
    },
    41: {
        "name": "Thomas Tuchel",
        "nationality": "Germany",
        "club": "Chelsea FC",
        "date_start": "2021-01-26",
        "date_end": "2022-09-07",
        "fotmob_id": 179347,
        "status": "memorable",
    },
    42: {
        "name": "Carlo Ancelotti",
        "nationality": "Italy",
        "club": "Chelsea FC",
        "date_start": "2009-07-01",
        "date_end": "2011-05-22",
        "fotmob_id": 78619,
        "status": "memorable",
    },
    43: {
        "name": "Sam Allardyce",
        "nationality": "England",
        "club": "Bolton Wanderers",
        "date_start": "1999-10-19",
        "date_end": "2007-05-30",
        "fotmob_id": 78740,
        "status": "memorable",
    },
    44: {
        "name": "Sam Allardyce",
        "nationality": "England",
        "club": "West Ham United",
        "date_start": "2011-11-07",
        "date_end": "2015-06-30",
        "fotmob_id": 78740,
        "status": "memorable",
    },
    45: {
        "name": "Sam Allardyce",
        "nationality": "England",
        "club": "Leeds United",
        "date_start": "2023-05-03",
        "date_end": "2023-06-30",
        "fotmob_id": 78740,
        "status": "memorable",
    },
    46: {
        "name": "Kevin Keegan",
        "nationality": "England",
        "club": "Newcastle United",
        "date_start": "1992-02-05",
        "date_end": "1997-01-08",
        "fotmob_id": None,
        "status": "memorable",
    },
    47: {
        "name": "Paul Jewell",
        "nationality": "England",
        "club": "Derby County",
        "date_start": "2007-11-28",
        "date_end": "2008-12-28",
        "fotmob_id": None,
        "status": "memorable",
    },
    48: {
        "name": "Jan Siewert",
        "nationality": "Germany",
        "club": "Huddersfield Town",
        "date_start": "2019-01-21",
        "date_end": "2019-08-16",
        "fotmob_id": 1017904,
        "status": "memorable",
    },
    49: {
        "name": "Les Reed",
        "nationality": "England",
        "club": "Charlton Athletic",
        "date_start": "2006-11-16",
        "date_end": "2006-12-24",
        "fotmob_id": None,
        "status": "memorable",
    },
    50: {
        "name": "Terry Connor",
        "nationality": "England",
        "club": "Wolverhampton Wanderers",
        "date_start": "2012-02-13",
        "date_end": "2012-06-30",
        "fotmob_id": None,
        "status": "memorable",
    },
    51: {
        "name": "Remi Garde",
        "nationality": "France",
        "club": "Aston Villa",
        "date_start": "2015-11-03",
        "date_end": "2016-03-29",
        "fotmob_id": 270666,
        "status": "memorable",
    },
    52: {
        "name": "Chris Hutchings",
        "nationality": "England",
        "club": "Wigan Athletic",
        "date_start": "2007-07-01",
        "date_end": "2007-11-05",
        "fotmob_id": None,
        "status": "memorable",
    },
    53: {
        "name": "Ole Gunnar Solskjaer",
        "nationality": "Norway",
        "club": "Cardiff City",
        "date_start": "2014-01-02",
        "date_end": "2014-09-18",
        "fotmob_id": None,
        "status": "memorable",
    },
    54: {
        "name": "Ole Gunnar Solskjaer",
        "nationality": "Norway",
        "club": "Manchester United",
        "date_start": "2018-12-19",
        "date_end": "2021-11-21",
        "fotmob_id": None,
        "status": "memorable",
    },
    55: {
        "name": "Bob Bradley",
        "nationality": "USA",
        "club": "Swansea City",
        "date_start": "2016-10-04",
        "date_end": "2016-12-27",
        "fotmob_id": 80653,
        "status": "memorable",
    },
    56: {
        "name": "Felix Magath",
        "nationality": "Germany",
        "club": "Fulham FC",
        "date_start": "2014-02-14",
        "date_end": "2014-10-18",
        "fotmob_id": 79318,
        "status": "memorable",
    },
    57: {
        "name": "Nathan Jones",
        "nationality": "Wales",
        "club": "Southampton FC",
        "date_start": "2022-11-10",
        "date_end": "2023-02-12",
        "fotmob_id": 519886,
        "status": "memorable",
    },
    58: {
        "name": "Paolo Di Canio",
        "nationality": "Italy",
        "club": "Sunderland AFC",
        "date_start": "2013-03-31",
        "date_end": "2013-09-22",
        "fotmob_id": 519886,
        "status": "memorable",
    },
    59: {
        "name": "René Meulensteen",
        "nationality": "Netherlands",
        "club": "Fulham FC",
        "date_start": "2013-12-01",
        "date_end": "2014-02-14",
        "fotmob_id": None,
        "status": "memorable",
    },
    60: {
        "name": "Juande Ramos",
        "nationality": "Spain",
        "club": "Tottenham Hotspur",
        "date_start": "2007-10-26",
        "date_end": "2008-10-27",
        "fotmob_id": None,
        "status": "memorable",
    },
    61: {
        "name": "André Villas-Boas",
        "nationality": "Portugal",
        "club": "Tottenham Hotspur",
        "date_start": "2012-07-03",
        "date_end": "2013-12-16",
        "fotmob_id": 204241,
        "status": "memorable",
    },
    62: {
        "name": "André Villas-Boas",
        "nationality": "Portugal",
        "club": "Chelsea FC",
        "date_start": "2011-07-01",
        "date_end": "2012-03-04",
        "fotmob_id": 204241,
        "status": "memorable",
    },
    63: {
        "name": "Nuno Espírito Santo",
        "nationality": "Portugal",
        "club": "Tottenham Hotspur",
        "date_start": "2021-07-01",
        "date_end": "2021-11-01",
        "fotmob_id": 361779,
        "status": "memorable",
    },
    64: {
        "name": "Alan Pardew",
        "nationality": "England",
        "club": "Newcastle United",
        "date_start": "2010-12-09",
        "date_end": "2015-01-02",
        "fotmob_id": 78637,
        "status": "memorable",
    },
    65: {
        "name": "Louis van Gaal",
        "nationality": "Netherlands",
        "club": "Manchester United",
        "date_start": "2014-07-14",
        "date_end": "2016-05-23",
        "fotmob_id": 109077,
        "status": "memorable",
    },
    66: {
        "name": "Mick McCarthy",
        "nationality": "Ireland",
        "club": "Wolverhampton Wanderers",
        "date_start": "2006-07-01",
        "date_end": "2012-02-13",
        "fotmob_id": 174657,
        "status": "memorable",
    },
    67: {
        "name": "Roberto Di Matteo",
        "nationality": "Italy",
        "club": "Chelsea FC",
        "date_start": "2012-03-04",
        "date_end": "2012-11-21",
        "fotmob_id": None,
        "status": "memorable",
    },
    68: {
        "name": "Avram Grant",
        "nationality": "Israel",
        "club": "Chelsea FC",
        "date_start": "2007-09-20",
        "date_end": "2008-05-24",
        "fotmob_id": None,
        "status": "memorable",
    },
    69: {
        "name": "Steven Gerrard",
        "nationality": "England",
        "club": "Aston Villa",
        "date_start": "2021-11-11",
        "date_end": "2022-10-20",
        "fotmob_id": None,
        "status": "memorable",
    },
    70: {
        "name": "Gary O'Neil",
        "nationality": "England",
        "club": "Wolverhampton Wanderers",
        "date_start": "2023-08-09",
        "fotmob_id": 24393,
        "status": "current",
    },
    71: {
        "name": "Kieran McKenna",
        "nationality": "Northern Ireland",
        "club": "Ipswich Town",
        "date_start": "2021-07-01",
        "fotmob_id": 1322897,
        "status": "current",
    },
    72: {
        "name": "Nuno Espirito Santo",
        "nationality": "Portugal",
        "club": "Nottingham Forest",
        "date_start": "2023-12-20",
        "fotmob_id": 25941,
        "status": "current",
    },
    73: {
        "name": "Arne Slot",
        "nationality": "Netherlands",
        "club": "Liverpool FC",
        "date_start": "2024-06-01",
        "fotmob_id": 26630,
        "status": "current",
    },
}
