current_managers = {
    "Jürgen Klopp": {
        "nationality": "Germany",
        "club": "Liverpool FC",
        "date_start": "2015-10-08",
        "fotmob_id": 78660,
    },
    "Pep Guardiola": {
        "nationality": "Spain",
        "club": "Manchester City FC",
        "date_start": "2016-07-01",
        "fotmob_id": 41636,
    },
    "Thomas Frank": {
        "nationality": "Denmark",
        "club": "Brentford FC",
        "date_start": "2018-10-16",
        "fotmob_id": 450969,
    },
    "Mikel Arteta": {
        "nationality": "Spain",
        "club": "Arsenal FC",
        "date_start": "2019-12-22",
        "fotmob_id": 24011,
    },
    "David Moyes": {
        "nationality": "Scotland",
        "club": "West Ham United FC",
        "date_start": "2019-12-30",
        "fotmob_id": 78626,
    },
    "Marco Silva": {
        "nationality": "Portugal",
        "club": "Fulham FC",
        "date_start": "2021-07-01",
        "fotmob_id": 164124,
    },
    "Steve Cooper": {
        "nationality": "Wales",
        "club": "Nottingham Forest FC",
        "date_start": "2021-09-21",
        "fotmob_id": 1061595,
    },
    "Eddie Howe": {
        "nationality": "England",
        "club": "Newcastle United FC",
        "date_start": "2021-11-08",
        "fotmob_id": 23630,
    },
    "Paul Heckingbottom": {
        "nationality": "England",
        "club": "Sheffield United FC",
        "date_start": "2021-11-25",
        "fotmob_id": 23250,
    },
    "Erik ten Hag": {
        "nationality": "Netherlands",
        "club": "Manchester United FC",
        "date_start": "2022-05-23",
        "fotmob_id": 656595,
    },
    "Vincent Kompany": {
        "nationality": "Belgium",
        "club": "Burnley FC",
        "date_start": "2022-06-14",
        "fotmob_id": 39027,
    },
    "Gary O'Neil": {
        "nationality": "England",
        "club": "AFC Bournemouth",
        "date_start": "2022-08-30",
        "fotmob_id": 24393,
    },
    "Roberto De Zerbi": {
        "nationality": "Italy",
        "club": "Brighton & Hove Albion FC",
        "date_start": "2022-09-18",
        "fotmob_id": 42044,
    },
    "Unai Emery": {
        "nationality": "Spain",
        "club": "Aston Villa FC",
        "date_start": "2022-11-01",
        "fotmob_id": 96940,
    },
    "Julen Lopetegui": {
        "nationality": "Spain",
        "club": "Wolverhampton Wanderers FC",
        "date_start": "2022-11-14",
        "fotmob_id": 396454,
    },
    "Rob Edwards": {
        "nationality": "Wales",
        "club": "Luton Town FC",
        "date_start": "2022-11-17",
        "fotmob_id": 1215524,
    },
    "Sean Dyche": {
        "nationality": "England",
        "club": "Everton FC",
        "date_start": "2023-01-30",
        "fotmob_id": 24581,
    },
    "Roy Hodgson": {
        "nationality": "England",
        "club": "Crystal Palace FC",
        "date_start": "2023-03-21",
        "fotmob_id": 98908,
    },
    "Ryan Mason": {
        "nationality": "England",
        "club": "Tottenham Hotspur FC",
        "date_start": "2023-04-24",
        "fotmob_id": 160448,
    },
    "Mauricio Pochettino": {
        "nationality": "Argentina",
        "club": "Chelsea FC",
        "date_start": "2023-05-29",
        "fotmob_id": 163300,
    },
}
